name: Deploy Azure Function

on:
  push:
    branches: [ main ]

env:
  AZURE_FUNCTIONAPP_NAME: 'azureimgproc'
  RESOURCE_GROUP: 'imgprocessorazure'
  STORAGE_ACCOUNT: 'mynewstorageacc'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Function
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: .
